# Generated by Django 5.2.18 on 2026-10-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_marketsnapshot_coin_circulating_supply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'ordering': ['-added_at']},
        ),
    ]
